### PR TITLE
bump to v1.4.11

### PR DESCRIPTION
**Pull request by carlodri**

### CODE REVIEW

**Comment by carlodri** [comment]
@jakirkham I am happy to try! As I told you in some other PR in some other feedstock, I still have a lot to learn, so I hope no one gets bumpy if I can't handle some maintenance issues....!

To add myself, I'll make a new PR with a [ci skip] trailing tag, correct?

**Comment by jakirkham** [comment]
No worries. If you need a hand, can always ping me (or core if I’m slow). ;) FWIW we are all learning here. :)

Yep that works or you can push the commit to this PR. Whichever is easiest. :)

Thanks @carlodri.

**Comment by carlodri** [comment]
@jakirkham I see that the autotick-bot PR failed the CI, while this one was succesfull. Since it seemed weird to me (the changeset is exactly the same), I reported the issue https://github.com/regro/cf-scripts/issues/46.

Can this manual PR be merged? Or in general one should wait for the bot PR to clear?

**Comment by jakirkham** [comment]
We will merge yours. After all you were here first. ;)

**Comment by jakirkham** [comment]
Thanks @carlodri.

**Pull request merged**
