### PR TITLE
Update to 1.4.19 and add pypy support

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@jakirkham, this is ready for review

**Comment by jaimergp** [comment]
I just released `menuinst` 1.4.19 with these patches, PR should arrive soon!

**Comment by isuruf** [comment]
Updated to 1.4.19. Ready for review.

**Review by jaimergp — APPROVED** [review]
LGTM!

**Comment by isuruf** [comment]
@jakirkham, can you review? I've added myself as a maintainer.

**Comment by isuruf** [comment]
Thanks @carlodri

**Pull request merged**
